/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkChangebagRouteImport } from './routes/work.changebag'
import { Route as WorkAgentdnaRouteImport } from './routes/work.agentdna'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkChangebagRoute = WorkChangebagRouteImport.update({
  id: '/work/changebag',
  path: '/work/changebag',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkAgentdnaRoute = WorkAgentdnaRouteImport.update({
  id: '/work/agentdna',
  path: '/work/agentdna',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work/agentdna': typeof WorkAgentdnaRoute
  '/work/changebag': typeof WorkChangebagRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work/agentdna': typeof WorkAgentdnaRoute
  '/work/changebag': typeof WorkChangebagRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work/agentdna': typeof WorkAgentdnaRoute
  '/work/changebag': typeof WorkChangebagRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/work/agentdna'
    | '/work/changebag'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/sitemap.xml' | '/work/agentdna' | '/work/changebag'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/work/agentdna'
    | '/work/changebag'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WorkAgentdnaRoute: typeof WorkAgentdnaRoute
  WorkChangebagRoute: typeof WorkChangebagRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/changebag': {
      id: '/work/changebag'
      path: '/work/changebag'
      fullPath: '/work/changebag'
      preLoaderRoute: typeof WorkChangebagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/agentdna': {
      id: '/work/agentdna'
      path: '/work/agentdna'
      fullPath: '/work/agentdna'
      preLoaderRoute: typeof WorkAgentdnaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WorkAgentdnaRoute: WorkAgentdnaRoute,
  WorkChangebagRoute: WorkChangebagRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
